/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyPhongKS;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class main extends javax.swing.JFrame {

     /**
      * Creates new form main
      */
     public main() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to
      * initialize the form. WARNING: Do NOT modify this code. The
      * content of this method is always regenerated by the Form
      * Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jButton1 = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();
          jMenuBar1 = new javax.swing.JMenuBar();
          jMenu1 = new javax.swing.JMenu();
          mnuItemDanhSach = new javax.swing.JMenuItem();
          mnuItemQuanLy = new javax.swing.JMenuItem();
          jSeparator1 = new javax.swing.JPopupMenu.Separator();
          mnuItemExit = new javax.swing.JMenuItem();
          jMenu2 = new javax.swing.JMenu();
          mnuItemGT = new javax.swing.JMenuItem();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter() {
               public void windowClosing(java.awt.event.WindowEvent evt) {
                    formWindowClosing(evt);
               }
          });

          jButton1.setText("Đăng xuất");

          jButton2.setText("Quản lý phòng ở");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          jButton3.setText("Danh sách phòng đã đặt");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(138, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jButton2)
                    .addGap(18, 18, 18)
                    .addComponent(jButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addContainerGap())
          );

          jMenu1.setText("Quản lý          ");

          mnuItemDanhSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
          mnuItemDanhSach.setText("Danh sách phòng");
          mnuItemDanhSach.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuItemDanhSachActionPerformed(evt);
               }
          });
          jMenu1.add(mnuItemDanhSach);

          mnuItemQuanLy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
          mnuItemQuanLy.setText("Quản lý phòng");
          mnuItemQuanLy.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuItemQuanLyActionPerformed(evt);
               }
          });
          jMenu1.add(mnuItemQuanLy);
          jMenu1.add(jSeparator1);

          mnuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
          mnuItemExit.setText("Exit");
          mnuItemExit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuItemExitActionPerformed(evt);
               }
          });
          jMenu1.add(mnuItemExit);

          jMenuBar1.add(jMenu1);

          jMenu2.setText("Giới thiệu");
          jMenu2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu2ActionPerformed(evt);
               }
          });

          mnuItemGT.setText("Giới thiêu phần mềm");
          mnuItemGT.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mnuItemGTActionPerformed(evt);
               }
          });
          jMenu2.add(mnuItemGT);

          jMenuBar1.add(jMenu2);

          setJMenuBar(jMenuBar1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          );

          pack();
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents

     private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

     }//GEN-LAST:event_jMenu2ActionPerformed

     private void mnuItemGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGTActionPerformed
          new GioiThieu().setVisible(true);
          new main().setVisible(true);
     }//GEN-LAST:event_mnuItemGTActionPerformed

     private void mnuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemExitActionPerformed
          int ret = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thoát chứ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (ret == JOptionPane.YES_OPTION) {
               System.exit(0);
          } else {
               JOptionPane.showMessageDialog(this, "Thao tác Exit đã hủy");
               setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
          }
     }//GEN-LAST:event_mnuItemExitActionPerformed

     private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
          int ret = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn thoát chứ?", "Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (ret == JOptionPane.YES_OPTION) {
               System.exit(0);
          } else {
               JOptionPane.showMessageDialog(this, "Thao tác Exit đã hủy");
               setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
          }
     }//GEN-LAST:event_formWindowClosing

     private void mnuItemDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemDanhSachActionPerformed
          this.dispose();
          new QuanLyChiTiet().setVisible(true);
     }//GEN-LAST:event_mnuItemDanhSachActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          this.dispose();
          new QuanLyChiTiet().setVisible(true);
     }//GEN-LAST:event_jButton3ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          this.dispose();
          new QuanLyPhong().setVisible(true);
     }//GEN-LAST:event_jButton2ActionPerformed

     private void mnuItemQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemQuanLyActionPerformed
          this.dispose();
          new QuanLyChiTiet().setVisible(true);
     }//GEN-LAST:event_mnuItemQuanLyActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new main().setVisible(false);
                    new Login().setVisible(true);
               }
          });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JMenu jMenu1;
     private javax.swing.JMenu jMenu2;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JSeparator jSeparator1;
     private javax.swing.JMenuItem mnuItemDanhSach;
     private javax.swing.JMenuItem mnuItemExit;
     private javax.swing.JMenuItem mnuItemGT;
     private javax.swing.JMenuItem mnuItemQuanLy;
     // End of variables declaration//GEN-END:variables
}
